# Generated by Django 4.2.3 on 2023-07-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('año_publicacion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('imagen', models.TextField()),
                ('descripcion', models.CharField(max_length=2500)),
                ('stock', models.IntegerField()),
                ('firmado', models.BooleanField(default=False)),
                ('hay_envio_gratis', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.autor')),
            ],
        ),
    ]
